name: Create Vesion Bump for Plante Moran Code Base
run-name: Create Version Bump for Plante Moran Code Base with Version v${{ inputs.versionTag }} by ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'
        required: true
        type: string
      versionTag:
        description: 'Create Version'
        required: true
        type: string
env:
    BRANCH: ${{ inputs.branch }}
    VERSION_TAG: ${{ inputs.versionTag }}
jobs:
    build-and-deploy-react-app:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [ 16.x ]
        steps:
        - name: Checkout Repository Via Tag
          uses: actions/checkout@v3
          
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Variable Subsitution
          run: |
            echo "Variable substitution happens here."
            echo "My code example is commented out."

        - name: File Check
          run: ls
    
        - name: Set CI to false
          run: echo "CI=false" >> $GITHUB_ENV

        - name: JSON Variable Substitution
          uses: microsoft/variable-substitution@v1
          with:
            files: 'package.json'
          env:
            version: ${{ env.VERSION_TAG }}

        - name: NPM Install & Build
          run: |
            npm install
            npm run build

        - name: Commit Changes
          run: |
            git checkout ${{ env.BRANCH }}
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git add .
            git commit -m "Bump version to $VERSION_TAG"
            git push

        - name: Deploy to Azure
          run: |
            echo "Hello, world"
            ls .
