name: Execute the If Statement Test
on:
  workflow_dispatch:
    inputs:
      api_scenario:
        description: API Scenario
        type: choice
        options:
          - apim
          - non-apim
        required: true
        default: apim

env:
  API_MANAGEMENT: ${{ inputs.api_scenario }}
  API_SCENARIO: apim

jobs:
  test-if-statement:
    name: The test
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/main' }} && env.API_MANAGEMENT == env.API_SCENARIO
    steps:
      - name: Run the test
        run: echo 'Run the test'
